export const formDynamicsReceiver = [
  {
    type: "text",
    placeholder: "Jenny Doe",
    name: "nameReceiver",
    error: undefined,
    label: "Nombre del destinatario",
  },
  {
    type: "document-id",
    placeholder: "12345678",
    name: "receiverId",
    error: undefined,
    label: "Cédula / RIF",
  },
  {
    type: "email",
    placeholder: "jennydoe@gmail.com (opcional)",
    name: "emailReceiver",
    error: undefined,
    label: "Email del destinatario (opcional)",
  },
  {
    type: "text",
    placeholder: "Calle 32, Av. Principal",
    name: "streetReceiver",
    error: undefined,
    label: "Dirección (opcional)",
  },
  {
    type: "text",
    placeholder: "Caracas",
    name: "cityReceiver",
    error: undefined,
    label: "Ciudad (opcional)",
  },
  {
    type: "text",
    placeholder: "Distrito Capital",
    name: "stateReceiver",
    error: undefined,
    label: "Estado / Provincia (opcional)",
  },
  {
    type: "text",
    placeholder: "Venezuela",
    name: "countryReceiver",
    error: undefined,
    label: "País (opcional)",
  },
];
